export const HomeActionTypes = {
    FETCH_MOVIES_START: 'FETCH_MOVIES_START',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',
    SEARCH_MOVIES: 'SEARCH_MOVIES',
    LOAD_MORE_MOVIES: 'LOAD_MORE_MOVIES',
    SHOW_LOADING_SPINNER: 'SHOW_LOADING_SPINNER',
    RESET_MOVIES: 'RESET_MOVIES'
}