export const HomeActionTypes = {
    FETCH_MOVIES: 'FETCH_MOVIES',
    SEARCH_MOVIES: 'SEARCH_MOVIES',
    LOAD_MORE_MOVIES: 'LOAD_MORE_MOVIES',
    SHOW_LOADING_SPINNER: 'SHOW_LOADING_SPINNER',
    RESET_MOVIES: 'RESET_MOVIES'
}